### ISSUE TITLE
Retain day of month for iteration

### ISSUE THREAD

**Issue by emj** [mvrozanti/dte#1]
This feels wrong

2014 Jan + 1M returns 2014-02-01
april+1M returns 2021-05-02

If I add 72 months will i get 72*31 days or 72*1month

**Comment by mvrozanti** [comment]
This is indeed controversial. The problem with month/year addition/subtraction is that the total period differs depending on the other operand. I'm having trouble keeping that sane, as you can tell.

This is definitely an enhancement opportunity

**Comment by mvrozanti** [comment]
I think this discussion is going to return but for now 5327c6e removes this particular inconsistency.
